import {createStandingsPanel} from './standings-ui.mjs';
import {SPORTS,LEAGUES,leaguesForSport,matchKey,parseFavorites,periodLabel,kstDate,validDate,shiftDate} from './sports.mjs';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const icons={ball:'<circle cx="12" cy="12" r="9"/><path d="m12 8 4 3-1.5 4.5h-5L8 11Zm0-5v5m8 2-4 1m1 9-2.5-4.5m-7 4.5 2.5-4.5M3 10l5 1"/>',star:'<path d="m12 3 2.8 5.8 6.4.9-4.6 4.5 1.1 6.4-5.7-3-5.7 3 1.1-6.4-4.6-4.5 6.4-.9Z"/>',arrow:'<path d="M4 12h16m-5-5 5 5-5 5"/>',refresh:'<path d="M20 7a9 9 0 0 0-15-2L3 7m0-5v5h5M4 17a9 9 0 0 0 15 2l2-2m0 5v-5h-5"/>','chevron-left':'<path d="m15 5-7 7 7 7"/>','chevron-right':'<path d="m9 5 7 7-7 7"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M8 3v4m8-4v4M3 11h18m-14 4h2m3 0h2"/>',search:'<circle cx="10" cy="10" r="6.5"/><path d="m15 15 6 6"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v.1"/>',globe:'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',external:'<path d="M14 3h7v7m0-7L10 14M10 3H3v18h18v-7"/>'};
Object.assign(icons,{
 basketball:'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3v18M5.5 5.5a9 9 0 0 1 0 13m13-13a9 9 0 0 0 0 13"/>',
 baseball:'<circle cx="12" cy="12" r="9"/><path d="M6 5a12 12 0 0 1 0 14M18 5a12 12 0 0 0 0 14M5 8l3 1m-3 3h3m-3 4 3-1m8-6 3-1m-3 4h3m-3 3 3 1"/>',
 football:'<path d="M3 21C-1 8 8-1 21 3c4 13-5 22-18 18Z"/><path d="m8 16 8-8m-8 4 4 4m-1-7 4 4M3 14l7 7M14 3l7 7"/>',
 hockey:'<path d="m17 3-5 14H3v4h10l8-18"/><ellipse cx="19" cy="20" rx="3" ry="1"/>'
});
const icon=name=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.ball}</svg>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={'Arsenal':'아스널','Aston Villa':'애스턴 빌라','Bournemouth':'본머스','Brentford':'브렌트퍼드','Brighton & Hove Albion':'브라이턴','Chelsea':'첼시','Crystal Palace':'크리스털 팰리스','Everton':'에버턴','Fulham':'풀럼','Leeds United':'리즈 유나이티드','Liverpool':'리버풀','Manchester City':'맨체스터 시티','Manchester United':'맨체스터 유나이티드','Newcastle United':'뉴캐슬','Nottingham Forest':'노팅엄 포리스트','Sunderland':'선덜랜드','Tottenham Hotspur':'토트넘','West Ham United':'웨스트햄','Wolverhampton Wanderers':'울버햄프턴','Burnley':'번리','Leicester City':'레스터 시티','Southampton':'사우샘프턴','Barcelona':'바르셀로나','Real Madrid':'레알 마드리드','Atlético Madrid':'아틀레티코 마드리드','Atletico Madrid':'아틀레티코 마드리드','Athletic Club':'아틀레틱 빌바오','Real Betis':'레알 베티스','Real Sociedad':'레알 소시에다드','Sevilla':'세비야','Valencia':'발렌시아','Villarreal':'비야레알','Girona':'지로나','Getafe':'헤타페','Celta Vigo':'셀타 비고','Espanyol':'에스파뇰','Osasuna':'오사수나','Mallorca':'마요르카','Rayo Vallecano':'라요 바예카노','Alavés':'알라베스','Bayern Munich':'바이에른 뮌헨','Borussia Dortmund':'도르트문트','Bayer Leverkusen':'레버쿠젠','RB Leipzig':'라이프치히','Eintracht Frankfurt':'프랑크푸르트','VfB Stuttgart':'슈투트가르트','Werder Bremen':'베르더 브레멘','VfL Wolfsburg':'볼프스부르크','SC Freiburg':'프라이부르크','1. FC Union Berlin':'우니온 베를린','Mainz':'마인츠','Internazionale':'인터 밀란','AC Milan':'AC 밀란','Juventus':'유벤투스','Napoli':'나폴리','AS Roma':'AS 로마','Lazio':'라치오','Atalanta':'아탈란타','Fiorentina':'피오렌티나','Bologna':'볼로냐','Genoa':'제노아','Torino':'토리노','Parma':'파르마','Udinese':'우디네세','Paris Saint-Germain':'파리 생제르맹','Marseille':'마르세유','AS Monaco':'AS 모나코','Lyon':'리옹','Lille':'릴','Lens':'랑스','Nice':'니스','Stade Rennais':'렌','Strasbourg':'스트라스부르','Ajax':'아약스','PSV Eindhoven':'PSV','Benfica':'벤피카','FC Porto':'포르투','Sporting CP':'스포르팅','Celtic':'셀틱'};
Object.assign(names,{
 'Atlanta Hawks':'애틀랜타 호크스','Boston Celtics':'보스턴 셀틱스','Brooklyn Nets':'브루클린 네츠','Charlotte Hornets':'샬럿 호네츠','Chicago Bulls':'시카고 불스','Cleveland Cavaliers':'클리블랜드 캐벌리어스','Dallas Mavericks':'댈러스 매버릭스','Denver Nuggets':'덴버 너기츠','Detroit Pistons':'디트로이트 피스턴스','Golden State Warriors':'골든스테이트 워리어스','Houston Rockets':'휴스턴 로키츠','Indiana Pacers':'인디애나 페이서스','LA Clippers':'LA 클리퍼스','Los Angeles Clippers':'LA 클리퍼스','Los Angeles Lakers':'LA 레이커스','Memphis Grizzlies':'멤피스 그리즐리스','Miami Heat':'마이애미 히트','Milwaukee Bucks':'밀워키 벅스','Minnesota Timberwolves':'미네소타 팀버울브스','New Orleans Pelicans':'뉴올리언스 펠리컨스','New York Knicks':'뉴욕 닉스','Oklahoma City Thunder':'오클라호마시티 썬더','Orlando Magic':'올랜도 매직','Philadelphia 76ers':'필라델피아 세븐티식서스','Phoenix Suns':'피닉스 선즈','Portland Trail Blazers':'포틀랜드 트레일블레이저스','Sacramento Kings':'새크라멘토 킹스','San Antonio Spurs':'샌안토니오 스퍼스','Toronto Raptors':'토론토 랩터스','Utah Jazz':'유타 재즈','Washington Wizards':'워싱턴 위저즈',
 'Los Angeles Dodgers':'LA 다저스','New York Yankees':'뉴욕 양키스','New York Mets':'뉴욕 메츠','San Diego Padres':'샌디에이고 파드리스','San Francisco Giants':'샌프란시스코 자이언츠','Boston Red Sox':'보스턴 레드삭스','Chicago Cubs':'시카고 컵스','Chicago White Sox':'시카고 화이트삭스','Philadelphia Phillies':'필라델피아 필리스','Atlanta Braves':'애틀랜타 브레이브스','Houston Astros':'휴스턴 애스트로스','Texas Rangers':'텍사스 레인저스','Seattle Mariners':'시애틀 매리너스','Toronto Blue Jays':'토론토 블루제이스','Milwaukee Brewers':'밀워키 브루어스','Cleveland Guardians':'클리블랜드 가디언스','Detroit Tigers':'디트로이트 타이거스','Baltimore Orioles':'볼티모어 오리올스','Tampa Bay Rays':'탬파베이 레이스','Minnesota Twins':'미네소타 트윈스','Kansas City Royals':'캔자스시티 로열스','Los Angeles Angels':'LA 에인절스','Athletics':'애슬레틱스','Arizona Diamondbacks':'애리조나 다이아몬드백스','Colorado Rockies':'콜로라도 로키스','Miami Marlins':'마이애미 말린스','Washington Nationals':'워싱턴 내셔널스','Cincinnati Reds':'신시내티 레즈','Pittsburgh Pirates':'피츠버그 파이리츠','St. Louis Cardinals':'세인트루이스 카디널스',
 'Kansas City Chiefs':'캔자스시티 치프스','Philadelphia Eagles':'필라델피아 이글스','Buffalo Bills':'버펄로 빌스','Dallas Cowboys':'댈러스 카우보이스','San Francisco 49ers':'샌프란시스코 포티나이너스','Baltimore Ravens':'볼티모어 레이븐스','Green Bay Packers':'그린베이 패커스','Detroit Lions':'디트로이트 라이언스','Minnesota Vikings':'미네소타 바이킹스','Seattle Seahawks':'시애틀 시호크스','Chicago Bears':'시카고 베어스','New England Patriots':'뉴잉글랜드 패트리어츠','New York Giants':'뉴욕 자이언츠','New York Jets':'뉴욕 제츠','Los Angeles Rams':'LA 램스','Los Angeles Chargers':'LA 차저스','Pittsburgh Steelers':'피츠버그 스틸러스','Denver Broncos':'덴버 브롱코스',
 'Edmonton Oilers':'에드먼턴 오일러스','Toronto Maple Leafs':'토론토 메이플리프스','Montreal Canadiens':'몬트리올 캐네이디언스','Vancouver Canucks':'밴쿠버 커넉스','Winnipeg Jets':'위니펙 제츠','Calgary Flames':'캘거리 플레임스','Ottawa Senators':'오타와 세너터스','New York Rangers':'뉴욕 레인저스','Detroit Red Wings':'디트로이트 레드윙스','Florida Panthers':'플로리다 팬서스','Vegas Golden Knights':'베이거스 골든나이츠','Colorado Avalanche':'콜로라도 애벌랜치','Boston Bruins':'보스턴 브루인스','Pittsburgh Penguins':'피츠버그 펭귄스','Utah Mammoth':'유타 매머드',
 'Las Vegas Aces':'라스베이거스 에이시스','New York Liberty':'뉴욕 리버티','Indiana Fever':'인디애나 피버','Minnesota Lynx':'미네소타 링스','Seattle Storm':'시애틀 스톰','Phoenix Mercury':'피닉스 머큐리','Los Angeles Sparks':'LA 스파크스','Chicago Sky':'시카고 스카이','Atlanta Dream':'애틀랜타 드림','Connecticut Sun':'코네티컷 선','Dallas Wings':'댈러스 윙스','Washington Mystics':'워싱턴 미스틱스'
});
const teamName=t=>names[t.name]||t.shortName||t.name;
const time=iso=>new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(iso));
const longDate=date=>new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'long',day:'numeric',weekday:'short'}).format(new Date(`${date}T12:00:00+09:00`));
const params=new URLSearchParams(location.search);
let selectedDate=validDate(params.get('date'))?params.get('date'):kstDate();
let selectedSport=SPORTS.some(s=>s.id===params.get('sport'))?params.get('sport'):LEAGUES.find(l=>l.id===params.get('league'))?.sport||'soccer';
let selectedLeague=leaguesForSport(selectedSport).some(l=>l.id===params.get('league'))?params.get('league'):'all';
let filter='all',favoritesOnly=false,query='',data=null,loading=false,error='',auto=true,nextRefresh=Date.now()+30000,requestId=0,controller,detailId=null,toastTimer;
const standingsPanel=createStandingsPanel({getSport:()=>selectedSport,getLeague:()=>selectedLeague,onLeagueChange:league=>{selectedLeague=league;updateURL();renderMatches();standingsPanel.sync();},teamName,logo,esc,time});
let favorites={};
try{favorites=parseFavorites(JSON.parse(localStorage.getItem('doyoon-score-favorites')||'{}'));}catch{}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3200);}
function updateURL(){const u=new URL(location.href);u.searchParams.set('date',selectedDate);u.searchParams.set('sport',selectedSport);if(selectedLeague==='all')u.searchParams.delete('league');else u.searchParams.set('league',selectedLeague);history.replaceState(null,'',u);}
function renderSports(){
 document.body.dataset.sport=selectedSport;
 const sport=SPORTS.find(s=>s.id===selectedSport);
 $('#sport-tabs').innerHTML=SPORTS.map(s=>{const saved=Object.values(favorites).filter(f=>f.sport===s.id).length;return `<button class="sport-button ${s.id===selectedSport?'selected':''}" data-sport="${s.id}" aria-pressed="${s.id===selectedSport}">${icon(s.icon)}<span>${s.name}</span><small>${favoritesOnly?`${saved}개 저장`:s.summary}</small></button>`;}).join('');
 $('#sport-guide').textContent=sport.guide;
 $('#results').setAttribute('aria-label',`${sport.name} 경기 목록`);
 document.title=`doyoon score — ${sport.name} 경기 결과`;
}
function setSport(sport){if(!SPORTS.some(s=>s.id===sport)||sport===selectedSport)return;selectedSport=sport;selectedLeague='all';filter='all';query='';$('#team-search').value='';renderFilters();updateURL();if($('#match-dialog').open)$('#match-dialog').close();loadScores(true);standingsPanel.sync();}
function badge(league){return `<span class="league-badge" style="--league-color:${league.color}">${league.code}</span>`;}
function renderLeagues(){$('#data-source').textContent=selectedLeague==='kbo'?'네이버 스포츠':selectedSport==='baseball'&&selectedLeague==='all'?'네이버 스포츠 · ESPN':'ESPN';const count=id=>data?data.matches.filter(m=>id==='all'||m.league===id).length:'—';$('#league-list').innerHTML=`<button class="league-button ${selectedLeague==='all'?'selected':''}" data-league="all" aria-pressed="${selectedLeague==='all'}">${icon(SPORTS.find(s=>s.id===selectedSport).icon)}<span>전체 리그</span><span>${count('all')}</span></button>`+leaguesForSport(selectedSport).map(l=>`<button class="league-button ${selectedLeague===l.id?'selected':''}" data-league="${l.id}" aria-pressed="${selectedLeague===l.id}">${badge(l)}<span>${l.name}</span><span>${data?.failures.some(f=>f.id===l.id)?'—':count(l.id)}</span></button>`).join('');}
function renderDates(){const today=kstDate();$('#date-input').value=selectedDate;$('#date-strip').innerHTML=Array.from({length:7},(_,i)=>{const d=shiftDate(selectedDate,i-3),dt=new Date(`${d}T12:00:00Z`);return `<button class="date-day ${d===selectedDate?'selected':''} ${d===today?'is-today':''}" data-date="${d}" aria-label="${esc(longDate(d))}" aria-pressed="${d===selectedDate}" ${!validDate(d)?'disabled':''}><small>${d===today?'오늘':['일','월','화','수','목','금','토'][dt.getUTCDay()]}</small><strong>${dt.getUTCDate()}</strong></button>`;}).join('');$('#previous-date').disabled=!validDate(shiftDate(selectedDate,-1));$('#next-date').disabled=!validDate(shiftDate(selectedDate,1));}
function logo(t){return `<span class="team-logo"><span class="logo-fallback" aria-hidden="true">${esc(t.abbreviation?.slice(0,3)||t.name.slice(0,2))}</span>${t.logo?`<img src="${esc(t.logo)}" alt="" width="28" height="28" loading="lazy" referrerpolicy="no-referrer">`:''}</span>`;}
function score(m){const played=['live','finished'].includes(m.status.state);return `<span class="score"><span class="score-line"><span>${played?m.home.score??'–':'–'}</span><span class="score-divider">:</span><span>${played?m.away.score??'–':'–'}</span></span>${m.home.penalties!==null&&m.away.penalties!==null?`<small>PK ${m.home.penalties} : ${m.away.penalties}</small>`:''}</span>`;}
function row(m){
 const state=m.status.state,live=state==='live';
 const primary=live?(m.status.phase||m.status.clock||'LIVE'):state==='finished'?'종료':state==='scheduled'?(m.timeTbd?'시간 미정':time(m.date)):m.status.label;
 const secondary=live&&m.sport!=='soccer'?(m.status.clock||'LIVE'):state==='scheduled'?'KST':m.timeTbd?'':time(m.date);
 const preseason=['preseason','pre-season'].includes(m.seasonType);
 return `<article class="match-row ${state}"><button class="match-main" data-match="${esc(m.id)}" aria-label="${esc(teamName(m.home))} ${m.home.score??''} 대 ${esc(teamName(m.away))} ${m.away.score??''}, ${esc(m.status.label)}, 경기 상세"><span class="match-status"><span>${esc(primary)}</span><small>${esc(secondary)}</small></span><span class="team home ${m.home.winner?'winner':''}"><span class="team-name">${esc(teamName(m.home))}</span>${logo(m.home)}</span><span class="score-group">${score(m)}${preseason?'<small class="season-tag">프리시즌</small>':''}</span><span class="team away ${m.away.winner?'winner':''}">${logo(m.away)}<span class="team-name">${esc(teamName(m.away))}</span></span><span class="match-chevron">${icon('chevron-right')}</span></button><button class="favorite-button" data-favorite="${esc(m.id)}" aria-label="${esc(teamName(m.home))} 대 ${esc(teamName(m.away))} 즐겨찾기 ${favorites[matchKey(m)]?'해제':'추가'}" aria-pressed="${!!favorites[matchKey(m)]}">${icon('star')}</button></article>`;
}
function segmentTable(m){
 if(m.sport==='soccer')return '';
 const periods=[...new Set([...m.home.segments,...m.away.segments].map(s=>s.period))].sort((a,b)=>a-b);
 if(!periods.length)return '';
 const caption=m.sport==='baseball'?'이닝별 득점':m.sport==='hockey'?'피리어드별 득점':'쿼터별 득점';
 const teamRow=t=>`<tr><th scope="row">${esc(teamName(t))}</th>${periods.map(p=>`<td>${esc(t.segments.find(s=>s.period===p)?.value??'–')}</td>`).join('')}<td class="total-score">${t.score??'–'}</td></tr>`;
 return `<div class="period-table-wrap" tabindex="0" aria-label="${caption}"><table class="period-table"><caption>${caption}</caption><thead><tr><th scope="col">팀</th>${periods.map(p=>`<th scope="col">${esc(periodLabel(m.sport,p))}</th>`).join('')}<th scope="col">합계</th></tr></thead><tbody>${teamRow(m.home)}${teamRow(m.away)}</tbody></table></div>`;
}

function empty(title,message,buttons='',type='ball'){return `<div class="empty-state"><span class="empty-icon">${icon(type)}</span><h3>${title}</h3><p>${message}</p>${buttons?`<div class="empty-actions">${buttons}</div>`:''}</div>`;}
const dateButton=(date,label)=>`<button class="small-button" data-date="${date}">${label}</button>`;
function renderMatches(){
 renderSports();renderLeagues();$('#board-title').textContent=favoritesOnly?'즐겨찾는 경기':`${SPORTS.find(s=>s.id===selectedSport).name} 경기 결과`;$('#favorite-count').textContent=Object.keys(favorites).length;
 $('#all-nav').classList.toggle('active',!favoritesOnly);$('#all-nav').setAttribute('aria-pressed',String(!favoritesOnly));$('#favorites-nav').classList.toggle('active',favoritesOnly);$('#favorites-nav').setAttribute('aria-pressed',String(favoritesOnly));
 const source=data?.date===selectedDate&&data.sport===selectedSport?data.matches:[];const base=source.filter(m=>(selectedLeague==='all'||m.league===selectedLeague)&&(!favoritesOnly||favorites[matchKey(m)]));
 for(const key of ['all','live','finished','scheduled'])$(`#count-${key}`).textContent=data?(key==='all'?base.length:base.filter(m=>m.status.state===key).length):'—';
 const needle=query.toLocaleLowerCase().replace(/\s/g,'');const matches=base.filter(m=>(filter==='all'||m.status.state===filter)&&(!needle||[m.home.name,m.away.name,m.home.shortName,m.away.shortName,teamName(m.home),teamName(m.away),m.home.abbreviation,m.away.abbreviation].some(n=>n.toLocaleLowerCase().replace(/\s/g,'').includes(needle))));
 $('#result-description').textContent=`${longDate(selectedDate)}${data?` · ${matches.length}경기`:''} · 한국 시간`;
 const missing=data?.failures||[];const unavailable=selectedLeague!=='all'&&missing.some(f=>f.id===selectedLeague);
 const notice=error?(data?'갱신에 실패했습니다. 아래는 마지막으로 받아온 기록입니다. ':'')+error:missing.length?`${missing.map(l=>l.name).join(', ')} 데이터를 불러오지 못했습니다. 해당 리그는 집계에서 제외되어 있습니다.`:'';
 $('#notice').hidden=!notice;$('#notice').textContent=notice;$('#update-status').classList.toggle('stale',!!error||missing.length>0);
 $('#updated-label').textContent=data?`${time(data.fetchedAt)} 확인${error?' · 갱신 실패':''}`:loading?'연결 중':'연결 실패';
 if(!data&&loading){$('#results').innerHTML='<div class="loading-state"><span class="loader"></span><strong>경기 정보를 가져오는 중</strong><p>최신 스코어를 확인하고 있어요.</p></div>';return;}
 if(!data||unavailable){$('#results').innerHTML=empty('경기 정보를 불러오지 못했어요','잠시 후 다시 시도해 주세요.','<button class="small-button" data-retry>다시 불러오기</button>','info');return;}
 if(!matches.length){let title='이 날짜에 등록된 경기가 없어요',message='다른 날짜를 선택해 경기 일정과 결과를 확인하세요.',buttons='';
  if(favoritesOnly){title='선택한 종목·날짜의 즐겨찾기가 없어요';message='경기 옆 별을 눌러 저장하거나, 저장한 경기 날짜를 선택하세요.';const dates=[...new Set(Object.values(favorites).filter(f=>f.sport===selectedSport).map(f=>f.date))].sort().reverse().slice(0,8);buttons=dates.map(d=>dateButton(d,longDate(d))).join('');}
  else if(query||filter!=='all'){title='조건에 맞는 경기가 없어요';message=filter==='live'?'선택한 날짜와 리그에 진행 중인 경기가 없습니다.':'검색어나 경기 상태 필터를 바꿔보세요.';buttons='<button class="small-button" data-clear-filters>전체 경기 보기</button>';}
  else{if(data.previousMatchDate&&selectedLeague!=='kbo')buttons+=dateButton(data.previousMatchDate,`${longDate(data.previousMatchDate)} 보기`);else buttons+=dateButton(shiftDate(selectedDate,-1),'이전 날짜 보기');if(selectedDate!==kstDate())buttons+=dateButton(kstDate(),'오늘로 이동');else if(data.nextMatchDate&&selectedLeague!=='kbo')buttons+=dateButton(data.nextMatchDate,'다음 경기일 보기');}
  $('#results').innerHTML=empty(title,message,buttons,favoritesOnly?'star':'calendar');return;
 }
 $('#results').innerHTML=leaguesForSport(selectedSport).map(l=>{const list=matches.filter(m=>m.league===l.id).sort((a,b)=>(a.status.state==='live'?-1:0)-(b.status.state==='live'?-1:0)||a.date.localeCompare(b.date));return list.length?`<section class="league-section" aria-label="${l.name}"><div class="league-heading">${badge(l)}<h3>${l.name}<small>${l.country}</small></h3><span class="match-count">${list.length}경기</span></div>${list.map(row).join('')}</section>`:'';}).join('');
}
function renderDetail(){const m=data?.matches.find(m=>m.id===detailId);if(!m)return;$('#detail-league').textContent=LEAGUES.find(l=>l.id===m.league)?.name||'';$('#match-detail').innerHTML=`<div class="detail-status">${esc(m.status.label)}${m.status.state==='live'&&m.status.clock?` · ${esc(m.status.clock)}`:''}</div><div class="detail-teams"><div class="detail-team">${logo(m.home)}<h3>${esc(teamName(m.home))}</h3><p>홈팀</p></div>${score(m)}<div class="detail-team">${logo(m.away)}<h3>${esc(teamName(m.away))}</h3><p>원정팀</p></div></div>${segmentTable(m)}<div class="detail-info"><p><strong>경기 시간</strong> · ${longDate(kstDate(m.date))} ${m.timeTbd?'시간 미정':time(m.date)+' (한국 시간)'}</p><p><strong>경기장</strong> · ${esc(m.venue||'제공된 정보가 없습니다')}</p>${m.note?`<p>${esc(m.note)}</p>`:''}</div>${m.detailUrl?`<div class="detail-source"><a class="small-button" href="${esc(m.detailUrl)}" target="_blank" rel="noopener noreferrer">${esc(m.source||'ESPN')}에서 상세 보기 ${icon('external')}</a></div>`:''}<p class="detail-fetched">${time(data.fetchedAt)} 확인 · 데이터 제공 상황에 따라 반영이 늦어질 수 있습니다.</p>`;}
async function loadScores(reset=false){const thisRequest=++requestId;controller?.abort();controller=new AbortController();const timeout=setTimeout(()=>controller?.signal.aborted||thisRequest!==requestId?null:controller.abort(),24000);loading=true;error='';if(reset)data=null;$('#results').setAttribute('aria-busy','true');$('#refresh-button').disabled=true;$('#refresh-button').classList.add('busy');renderMatches();
 try{const response=await fetch(`/api/scores?date=${selectedDate}&sport=${selectedSport}`,{signal:controller.signal,headers:{Accept:'application/json'},cache:'no-store'});const json=await response.json();if(thisRequest!==requestId)return;if(!response.ok)throw new Error(json.error||'경기 데이터를 가져오지 못했습니다.');if(json.date!==selectedDate||json.sport!==selectedSport||!Array.isArray(json.matches)||!Array.isArray(json.failures))throw new Error('경기 데이터의 형식을 확인할 수 없습니다.');data=json;error='';}
 catch(e){if(thisRequest!==requestId)return;error=e.name==='AbortError'?'응답 시간이 초과되었습니다. 다시 시도해 주세요.':e instanceof SyntaxError?'서버 응답을 읽지 못했습니다. 다시 시도해 주세요.':e.message||'네트워크 연결을 확인해 주세요.';}
 finally{clearTimeout(timeout);if(thisRequest===requestId){loading=false;nextRefresh=Date.now()+30000;$('#results').setAttribute('aria-busy','false');$('#refresh-button').disabled=false;$('#refresh-button').classList.remove('busy');renderMatches();if($('#match-dialog').open)renderDetail();renderCountdown();}}
}
function setDate(date){if(!validDate(date))return;selectedDate=date;renderDates();updateURL();if($('#match-dialog').open)$('#match-dialog').close();loadScores(true);}
function showFavorites(value){favoritesOnly=value;filter='all';query='';$('#team-search').value='';renderFilters();renderMatches();}
function renderFilters(){$$('[data-filter]').forEach(el=>{el.classList.toggle('selected',el.dataset.filter===filter);el.setAttribute('aria-pressed',String(el.dataset.filter===filter));});}
function renderCountdown(){const left=Math.max(0,Math.ceil((nextRefresh-Date.now())/1000));$('#countdown').textContent=loading?'…':auto?left:'—';$('#refresh-progress').style.width=`${auto?left/30*100:0}%`;$('#refresh-caption').textContent=loading?'데이터를 확인하는 중':auto?'다음 갱신까지':'자동 갱신 일시 정지';$('.live-panel>strong').textContent=auto?'스코어, 계속 확인 중':'필요할 때 새로고침';$('#auto-toggle').setAttribute('aria-checked',String(auto));$('#mobile-auto-toggle').setAttribute('aria-pressed',String(auto));$('#mobile-auto-toggle').textContent=auto?'자동 갱신 켜짐':'자동 갱신 꺼짐';}
document.addEventListener('click',e=>{const sport=e.target.closest('[data-sport]');if(sport&&sport!==document.body){setSport(sport.dataset.sport);return;}const date=e.target.closest('[data-date]');if(date){setDate(date.dataset.date);return;}const league=e.target.closest('[data-league]');if(league){selectedLeague=league.dataset.league;updateURL();renderMatches();standingsPanel.sync();return;}const f=e.target.closest('[data-filter]');if(f){filter=f.dataset.filter;renderFilters();renderMatches();return;}if(e.target.closest('[data-retry]'))loadScores();if(e.target.closest('[data-clear-filters]')){filter='all';query='';$('#team-search').value='';renderFilters();renderMatches();}const favorite=e.target.closest('[data-favorite]');if(favorite){const id=favorite.dataset.favorite;const match=data?.matches.find(m=>m.id===id);if(!match)return;const key=matchKey(match);if(favorites[key])delete favorites[key];else favorites[key]={date:kstDate(match.date),sport:match.sport};try{localStorage.setItem('doyoon-score-favorites',JSON.stringify(favorites));}catch{toast('브라우저 저장 공간을 사용할 수 없습니다.');}renderMatches();return;}const match=e.target.closest('[data-match]');if(match){detailId=match.dataset.match;renderDetail();$('#match-dialog').showModal();}});
document.addEventListener('error',e=>{if(e.target instanceof HTMLImageElement)e.target.hidden=true;},true);
$('#date-input').onchange=e=>{if(validDate(e.target.value))setDate(e.target.value);else e.target.value=selectedDate;};
$('#previous-date').onclick=()=>setDate(shiftDate(selectedDate,-1));$('#next-date').onclick=()=>setDate(shiftDate(selectedDate,1));
$('#refresh-button').onclick=()=>loadScores();$('#team-search').oninput=e=>{query=e.target.value;renderMatches();};
$('#all-nav').onclick=()=>showFavorites(false);$('#favorites-nav').onclick=()=>showFavorites(true);$('#side-favorites').onclick=()=>{showFavorites(true);$('#board-title').scrollIntoView({behavior:'smooth',block:'start'});};
function toggleAuto(){auto=!auto;nextRefresh=Date.now()+30000;renderCountdown();}$('#auto-toggle').onclick=toggleAuto;$('#mobile-auto-toggle').onclick=toggleAuto;$('#close-detail').onclick=()=>$('#match-dialog').close();
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&auto&&!loading)loadScores();});window.addEventListener('online',()=>{if(!loading)loadScores();});
window.addEventListener('storage',e=>{if(e.key==='doyoon-score-favorites'){try{favorites=parseFavorites(JSON.parse(e.newValue||'{}'));renderMatches();}catch{}}});
$$('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));renderDates();renderMatches();loadScores(true);standingsPanel.sync();
setInterval(()=>{renderCountdown();if(auto&&!loading&&!document.hidden&&Date.now()>=nextRefresh)loadScores();},1000);

setInterval(()=>{if(auto&&!document.hidden)standingsPanel.refreshIfDue();},30000);
