import test from 'node:test';
import assert from 'node:assert/strict';
import {LEAGUES,kstDate,validDate,queryDates,normalizeEvent,parseLeague,matchStatus} from '../sports.mjs';
import {handler,getScores} from '../api/scores.js';
const league=LEAGUES[0];
function event(date='2026-10-04T16:00:00Z',state='post',completed=true){return {id:'123',date,status:{type:{state,completed,name:completed?'STATUS_FULL_TIME':'STATUS_SCHEDULED'}},competitions:[{competitors:[{homeAway:'away',score:'2',team:{id:'2',displayName:'Away',logo:'https://a.espncdn.com/test.png'}},{homeAway:'home',score:'0',team:{id:'1',displayName:'Home'}}]}]};}
const payload=(events=[])=>({leagues:[{calendar:['2026-10-04T07:00:00Z','2026-10-10T07:00:00Z']}],events});
test('Korean dates include matches played on the previous UTC day',()=>{assert.equal(kstDate('2026-10-04T15:00:00Z'),'2026-10-05');assert.equal(kstDate('2026-10-04T14:59:59Z'),'2026-10-04');const out=parseLeague(payload([event(),event('2026-10-05T16:00:00Z')]),league,'2026-10-05');assert.equal(out.matches.length,1);assert.deepEqual(queryDates('2026-10-05'),['20261004','20261005']);});
test('scores align by homeAway rather than upstream competitor order',()=>{const m=normalizeEvent(event(),league);assert.equal(m.home.name,'Home');assert.equal(m.home.score,0);assert.equal(m.away.score,2);});
test('a scheduled 0–0 is not displayed as an actual result',()=>{const m=normalizeEvent(event(undefined,'pre',false),league);assert.equal(m.status.state,'scheduled');assert.equal(m.home.score,null);assert.equal(m.away.score,null);});
test('postponed and canceled fixtures cannot become final results',()=>{assert.equal(matchStatus({type:{state:'post',completed:true,name:'STATUS_POSTPONED'}}).state,'other');assert.equal(matchStatus({type:{name:'STATUS_CANCELED'}}).label,'취소');});
test('live clock, half-time and penalty shootout remain distinguishable',()=>{const live=matchStatus({type:{state:'in',name:'STATUS_IN_PROGRESS'},displayClock:"67'"});assert.equal(live.clock,"67'");assert.equal(live.state,'live');assert.equal(matchStatus({type:{state:'in',name:'STATUS_HALFTIME'}}).label,'하프타임');const e=event();e.status.type.name='STATUS_FINAL_PEN';e.competitions[0].competitors[0].shootoutScore='5';e.competitions[0].competitors[1].shootoutScore='4';const m=normalizeEvent(e,league);assert.equal(m.status.label,'승부차기 종료');assert.equal(m.home.penalties,4);assert.equal(m.away.penalties,5);});
test('bad upstream payload is an error, valid no-event payload is empty',()=>{assert.throws(()=>parseLeague({error:'Unavailable'},league,'2026-10-05'));assert.equal(parseLeague(payload(),league,'2026-10-05').matches.length,0);});
test('upstream links are restricted to HTTPS ESPN hosts',()=>{const e=event();e.links=[{rel:['summary'],href:'javascript:alert(1)'}];e.competitions[0].competitors[0].team.logo='https://evil.example/image';const m=normalizeEvent(e,league);assert.equal(m.detailUrl,'');assert.equal(m.away.logo,'');});
test('date and league validation happen before making upstream requests',async()=>{let calls=0;const f=async()=>{calls++;return Response.json(payload());};for(const query of ['date=2026-02-31','date=2026-10-05&league=https://evil.example']){const r=await handler(new Request('https://site.test/api/scores?'+query),f);assert.equal(r.status,400);}assert.equal(calls,0);assert.equal(validDate('2026-10-05'),true);assert.equal(validDate('2026-02-31'),false);});
test('partial upstream failures preserve available data and identify missing leagues',async()=>{const result=await getScores('2026-10-05','all',async url=>{if(url.includes('/eng.1/'))return Response.json(payload([event()]));throw new Error('offline');});assert.equal(result.matches.length,1);assert.equal(result.loadedLeagues.length,1);assert.equal(result.failures.length,5);});
test('total upstream failure returns 502 rather than an empty match day',async()=>{const r=await handler(new Request('https://site.test/api/scores?date=2026-10-05'),async()=>{throw new Error('offline');});assert.equal(r.status,502);assert.equal(r.headers.get('cache-control'),'no-store');assert.ok((await r.json()).error);});
test('valid empty responses remain successful, and writes are rejected',async()=>{const r=await handler(new Request('https://site.test/api/scores?date=2026-10-05'),async()=>Response.json(payload()));assert.equal(r.status,200);assert.equal((await r.json()).matches.length,0);const write=await handler(new Request('https://site.test/api/scores',{method:'POST'}));assert.equal(write.status,405);});
